"""Views, one for each wraqStats page."""
from wraqStats.views.indextemp import show_hello
from wraqStats.views.index import show_index
from wraqStats.views.index import get_photo
from wraqStats.views.postreqs import post_like
from wraqStats.views.user import show_followers
from wraqStats.views.user import show_following
from wraqStats.views.user import show_user
from wraqStats.views.post import show_posts
from wraqStats.views.postreqs import post_like
from wraqStats.views.postreqs import post_comment
from wraqStats.views.postreqs import follow_request
from wraqStats.views.accounts import acc_login
from wraqStats.views.accounts import acc_create
from wraqStats.views.accounts import acc_delete
from wraqStats.views.accounts import acc_edit
from wraqStats.views.accounts import acc_password
from wraqStats.views.accounts import acc_postreq
from wraqStats.views.accounts import acc_logout
from wraqStats.views.postreqs import post_post