"""Views, one for each Insta485 page."""
from insta485.views.indextemp import show_hello
from insta485.views.index import show_index
from insta485.views.index import get_photo
from insta485.views.postreqs import post_like
from insta485.views.user import show_followers
from insta485.views.user import show_following
from insta485.views.user import show_user
from insta485.views.post import show_posts
from insta485.views.postreqs import post_like
from insta485.views.postreqs import post_comment
from insta485.views.postreqs import follow_request
from insta485.views.accounts import acc_login
from insta485.views.accounts import acc_create
from insta485.views.accounts import acc_delete
from insta485.views.accounts import acc_edit
from insta485.views.accounts import acc_password
from insta485.views.accounts import acc_postreq
from insta485.views.accounts import acc_logout
from insta485.views.postreqs import post_post